// FAQ Knowledge Base — 35 questions across 7 categories
export interface FAQQuestion {
  id: string;
  category: "pvt-ltd" | "llp" | "opc" | "section8" | "gst-tax" | "roc" | "trademark";
  question: string;
  bluf: string;
  detail: string; // HTML-safe markdown-like content
  relatedIds: string[]; // People also ask
  serviceLink: string;
  serviceName: string;
  tags: string[];
  lastUpdated: string;
}

export const FAQ_CATEGORIES = [
  { id: "all", label: "All Topics", count: 35 },
  { id: "pvt-ltd", label: "Pvt Ltd Company", count: 8 },
  { id: "llp", label: "LLP Partnership", count: 6 },
  { id: "opc", label: "OPC (One Person)", count: 5 },
  { id: "section8", label: "Section 8 NGO", count: 4 },
  { id: "gst-tax", label: "GST & Tax", count: 5 },
  { id: "roc", label: "ROC Compliance", count: 4 },
  { id: "trademark", label: "Trademark", count: 3 },
] as const;

export const FAQ_DATA: FAQQuestion[] = [
  // ═══ PVT LTD (8) ═══
  {
    id: "pvt-1",
    category: "pvt-ltd",
    question: "How long does online company registration take in India?",
    bluf: "Online Pvt Ltd company registration takes 7–10 working days, including DSC acquisition, SPICe+ Part A name approval, and Part B final filing with ROC.",
    detail: `The process has 3 phases:\n• Phase 1 (1-2 days): Digital Signature Certificate (DSC) & DIN allocation\n• Phase 2 (2-3 days): SPICe+ Part A — name reservation with Central Registration Centre\n• Phase 3 (3-5 days): SPICe+ Part B — MOA, AOA, AGILE-PRO-S filing, PAN & TAN issuance\n\nOver 94% of applications get approved in a single filing. Ensure utility bills are under 60 days old.`,
    relatedIds: ["pvt-2", "pvt-3", "pvt-5"],
    serviceLink: "/services",
    serviceName: "Start Pvt Ltd Registration",
    tags: ["registration", "timeline", "SPICe+"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "pvt-2",
    category: "pvt-ltd",
    question: "What is the minimum capital required for a Private Limited Company?",
    bluf: "There is no minimum paid-up capital requirement for Pvt Ltd companies in India since 2015. You can incorporate with as low as ₹1,000 in share capital.",
    detail: `The Companies (Amendment) Act 2015 removed the ₹1 lakh minimum capital requirement.\n\n• You can start with any amount (even ₹1,000)\n• Authorized capital determines stamp duty fees\n• Higher capital = more credibility with banks and investors\n• Recommended: ₹1 lakh for bank account opening ease\n\nNote: Stamp duty is calculated on authorized capital, not paid-up capital.`,
    relatedIds: ["pvt-1", "pvt-4", "pvt-6"],
    serviceLink: "/services",
    serviceName: "Calculate Registration Fees",
    tags: ["capital", "investment", "shares"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "pvt-3",
    category: "pvt-ltd",
    question: "What documents are needed for Pvt Ltd company registration?",
    bluf: "You need PAN, Aadhaar, passport-size photo, bank statement (under 2 months), utility bill for office address, and NOC from property owner.",
    detail: `Director Documents:\n• PAN Card (mandatory)\n• Aadhaar Card or Passport\n• Latest bank statement (address proof, under 2 months)\n• Passport-size photograph (digital JPG)\n\nRegistered Office Documents:\n• Electricity/water bill (under 2 months old)\n• NOC from landlord (signed)\n• Rent agreement or ownership proof\n\nAdditional:\n• Form DIR-2 (Consent to act as Director)\n• Form INC-9 (Declaration by subscribers)`,
    relatedIds: ["pvt-1", "pvt-4", "opc-1"],
    serviceLink: "/services",
    serviceName: "Upload Documents & Start",
    tags: ["documents", "KYC", "requirements"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "pvt-4",
    category: "pvt-ltd",
    question: "How many directors are required for a Private Limited Company?",
    bluf: "Minimum 2 directors and 2 shareholders are required. At least one director must be an Indian resident (stayed in India for 120+ days in the previous year).",
    detail: `Requirements:\n• Minimum 2 directors (maximum 15)\n• Minimum 2 shareholders (can be same as directors)\n• At least 1 director must be Indian resident\n• Directors must have valid DIN (Director Identification Number)\n• Each director needs a Class 3 Digital Signature Certificate (DSC)\n\nNote: A single person can be both a director and shareholder. For solo founders, consider OPC instead.`,
    relatedIds: ["pvt-3", "opc-1", "pvt-5"],
    serviceLink: "/services",
    serviceName: "Pvt Ltd Registration",
    tags: ["directors", "shareholders", "requirements"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "pvt-5",
    category: "pvt-ltd",
    question: "What is the cost of registering a Private Limited Company?",
    bluf: "Total cost ranges from ₹6,000 to ₹15,000 depending on state stamp duty, authorized capital, and professional fees. Government fees alone are ₹3,000–₹5,000.",
    detail: `Cost Breakdown:\n• ROC filing fee: ₹1,000 (fixed)\n• Stamp duty: ₹1,000–₹5,000 (varies by state & capital)\n• DSC: ₹1,500–₹3,000 (for 2 directors)\n• PAN/TAN application: ₹150\n• Professional fee (Incroute): ₹999\n\nState-wise stamp duty varies significantly. Maharashtra and Karnataka charge higher rates. Use our Stamp Duty Calculator for exact estimates.`,
    relatedIds: ["pvt-2", "pvt-1", "pvt-6"],
    serviceLink: "/tools",
    serviceName: "Use Stamp Duty Calculator",
    tags: ["cost", "fees", "stamp duty"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "pvt-6",
    category: "pvt-ltd",
    question: "Can NRIs or foreign nationals be directors in an Indian Pvt Ltd?",
    bluf: "Yes, NRIs and foreign nationals can be directors. However, at least one director must be an Indian resident. Foreign directors need a valid passport and FIPB/RBI approval for FDI.",
    detail: `Rules for foreign directors:\n• Must have a valid passport (notarized & apostilled)\n• Need a DIN (Director Identification Number)\n• DSC from Indian certifying authority\n• At least 1 director must be Indian resident (120+ days in India)\n• FDI compliance under FEMA regulations\n• No Indian PAN required initially (can apply later)\n\nFor 100% foreign-owned companies, automatic route FDI is available in most sectors.`,
    relatedIds: ["pvt-4", "pvt-3", "pvt-7"],
    serviceLink: "/services",
    serviceName: "NRI Company Registration",
    tags: ["NRI", "foreign", "FDI"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "pvt-7",
    category: "pvt-ltd",
    question: "What is the difference between Authorized and Paid-up Capital?",
    bluf: "Authorized capital is the maximum shares a company CAN issue. Paid-up capital is what shareholders have ACTUALLY paid. Stamp duty is charged on authorized capital.",
    detail: `Key differences:\n\n• Authorized Capital: Maximum limit of shares the company can ever issue. Set in MOA. Increasing it later requires ROC filing + additional stamp duty.\n\n• Paid-up Capital: Actual money deposited by shareholders into the company bank account. Must be ≤ authorized capital.\n\n• Subscribed Capital: Shares allocated to shareholders but not yet fully paid.\n\nExample: Authorized ₹10L, Paid-up ₹1L means you've issued ₹1L worth of shares but can issue up to ₹10L without ROC amendment.`,
    relatedIds: ["pvt-2", "pvt-5", "pvt-8"],
    serviceLink: "/services",
    serviceName: "Capital Structure Advisory",
    tags: ["capital", "shares", "MOA"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "pvt-8",
    category: "pvt-ltd",
    question: "Can I convert my sole proprietorship to a Pvt Ltd company?",
    bluf: "Yes, you can convert a sole proprietorship to Pvt Ltd. The process involves fresh incorporation (not a direct conversion) and transferring assets/liabilities to the new entity.",
    detail: `Steps to convert:\n1. Incorporate a new Pvt Ltd company (standard SPICe+ process)\n2. Open a corporate bank account\n3. Transfer all assets, contracts, and liabilities via a Business Transfer Agreement\n4. Close the proprietorship's GST registration and apply for new GST under the company\n5. Update all vendor/client contracts\n6. File final ITR for the proprietorship\n\nTimeline: 15-20 days total. The proprietorship ceases to exist after transfer.`,
    relatedIds: ["pvt-1", "pvt-5", "opc-2"],
    serviceLink: "/services",
    serviceName: "Conversion Advisory",
    tags: ["conversion", "proprietorship", "migration"],
    lastUpdated: "2026-05-31",
  },
  // ═══ LLP (6) ═══
  {
    id: "llp-1",
    category: "llp",
    question: "What is the minimum number of partners required for an LLP?",
    bluf: "Minimum 2 designated partners are required. At least one must be an Indian resident. There is no maximum limit on partners.",
    detail: `LLP Partner Requirements:\n• Minimum 2 Designated Partners (DPs)\n• At least 1 DP must be Indian resident (182+ days in India)\n• No maximum limit on total partners\n• Partners can be individuals or body corporates\n• Each DP needs a DPIN (Designated Partner Identification Number)\n• Class 3 DSC required for e-filing\n\nUnlike Pvt Ltd, LLP partners have flexible profit-sharing ratios defined in the LLP Agreement.`,
    relatedIds: ["llp-2", "llp-3", "pvt-4"],
    serviceLink: "/services",
    serviceName: "LLP Registration",
    tags: ["partners", "requirements", "DPIN"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "llp-2",
    category: "llp",
    question: "Is audit mandatory for an LLP?",
    bluf: "Audit is mandatory only if LLP turnover exceeds ₹40 lakhs OR capital contribution exceeds ₹25 lakhs. Below these thresholds, no statutory audit is required.",
    detail: `Audit thresholds:\n• Turnover > ₹40 lakhs in any financial year → Audit mandatory\n• Capital contribution > ₹25 lakhs → Audit mandatory\n• If BOTH are below limits → No audit required\n\nEven without audit, LLPs must file:\n• Form 8 (Statement of Accounts & Solvency) — by October 30\n• Form 11 (Annual Return) — by May 30\n• Income Tax Return — by July 31\n\nThis makes LLP significantly cheaper to maintain than Pvt Ltd for small businesses.`,
    relatedIds: ["llp-1", "llp-4", "roc-1"],
    serviceLink: "/services",
    serviceName: "LLP Compliance Package",
    tags: ["audit", "compliance", "threshold"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "llp-3",
    category: "llp",
    question: "Can an LLP be converted to a Private Limited Company?",
    bluf: "Yes, an LLP can be converted to Pvt Ltd under Section 366 of the Companies Act, 2013. All partners become shareholders and the LLP ceases to exist.",
    detail: `Conversion process:\n1. Pass a resolution among all partners\n2. File Form URC-1 with ROC\n3. Submit LLP Agreement, financial statements, and partner consent\n4. ROC issues Certificate of Incorporation\n5. LLP is dissolved automatically\n\nConditions:\n• All partners must consent\n• No pending regulatory actions against the LLP\n• All statutory filings must be up to date\n\nTimeline: 30-45 days. Recommended when seeking VC funding.`,
    relatedIds: ["llp-1", "pvt-1", "llp-5"],
    serviceLink: "/services",
    serviceName: "LLP to Pvt Ltd Conversion",
    tags: ["conversion", "Pvt Ltd", "Section 366"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "llp-4",
    category: "llp",
    question: "What annual filings are required for an LLP?",
    bluf: "LLPs must file Form 8 (Statement of Accounts) by October 30 and Form 11 (Annual Return) by May 30 every year, plus Income Tax Return by July 31.",
    detail: `Mandatory annual filings:\n\n1. Form 8 — Statement of Accounts & Solvency\n   • Due: October 30 (for FY ending March 31)\n   • Penalty: ₹100/day for late filing\n\n2. Form 11 — Annual Return\n   • Due: May 30\n   • Penalty: ₹100/day\n\n3. Income Tax Return (ITR-5)\n   • Due: July 31 (non-audit) or October 31 (audit cases)\n\n4. DIR-3 KYC (for each Designated Partner)\n   • Due: September 30\n\nMissing filings can lead to LLP strike-off after 2 consecutive years.`,
    relatedIds: ["llp-2", "roc-1", "roc-2"],
    serviceLink: "/services",
    serviceName: "Annual Compliance Package",
    tags: ["filings", "Form 8", "Form 11", "compliance"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "llp-5",
    category: "llp",
    question: "What is the LLP Agreement and is it mandatory?",
    bluf: "The LLP Agreement defines partner rights, profit-sharing, and management structure. It must be filed with ROC within 30 days of incorporation (Form 3).",
    detail: `The LLP Agreement covers:\n• Names and contributions of all partners\n• Profit/loss sharing ratio\n• Rights and duties of designated partners\n• Admission/retirement of partners procedure\n• Dispute resolution mechanism\n• Winding up provisions\n\nFiling:\n• Must be filed as Form 3 within 30 days of incorporation\n• Penalty for late filing: ₹100/day\n• Must be printed on stamp paper (value varies by state)\n\nWithout a filed agreement, the default Schedule I of the LLP Act applies (equal sharing).`,
    relatedIds: ["llp-1", "llp-4", "llp-6"],
    serviceLink: "/services",
    serviceName: "Draft LLP Agreement",
    tags: ["agreement", "Form 3", "partnership deed"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "llp-6",
    category: "llp",
    question: "Can an LLP raise venture capital or angel investment?",
    bluf: "LLPs cannot issue equity shares, making VC/angel investment extremely difficult. Investors strongly prefer Pvt Ltd structure for equity-based funding rounds.",
    detail: `Why LLPs struggle with funding:\n• No concept of "shares" — only capital contribution\n• Cannot issue ESOPs to employees\n• No clear exit mechanism for investors\n• Most VC term sheets require Pvt Ltd or C-Corp structure\n• Convertible notes don't work cleanly with LLPs\n\nAlternatives:\n• Convert LLP to Pvt Ltd before fundraising\n• Use revenue-based financing (no equity dilution)\n• Partner contribution increase (but no equity upside for investor)\n\nRecommendation: If you plan to raise funding within 2 years, start as Pvt Ltd.`,
    relatedIds: ["llp-3", "pvt-1", "pvt-2"],
    serviceLink: "/services",
    serviceName: "Pvt Ltd Registration",
    tags: ["funding", "VC", "investment", "equity"],
    lastUpdated: "2026-05-31",
  },
  // ═══ OPC (5) ═══
  {
    id: "opc-1",
    category: "opc",
    question: "What documents are needed for OPC registration?",
    bluf: "OPC requires director's PAN, Aadhaar, photo, bank statement, utility bill for office, NOC from landlord, and Form INC-3 (Nominee Consent).",
    detail: `Sole Director Documents:\n• PAN Card (mandatory)\n• Aadhaar Card or Passport\n• Bank statement (under 2 months, address proof)\n• Passport-size photo (digital)\n\nNominee Director Documents:\n• PAN & Aadhaar of nominee\n• Form INC-3 (signed consent to act as nominee)\n\nRegistered Office:\n• Electricity/water bill (under 2 months)\n• NOC from property owner\n• Rent agreement (if applicable)\n\nThe nominee takes over if the sole director becomes incapacitated.`,
    relatedIds: ["opc-2", "pvt-3", "opc-3"],
    serviceLink: "/services",
    serviceName: "OPC Registration",
    tags: ["documents", "nominee", "KYC"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "opc-2",
    category: "opc",
    question: "When must an OPC convert to a Private Limited Company?",
    bluf: "OPC must convert to Pvt Ltd if paid-up capital exceeds ₹50 lakhs OR annual turnover exceeds ₹2 crores. Conversion must happen within 6 months of crossing the threshold.",
    detail: `Mandatory conversion triggers:\n• Paid-up capital > ₹50 lakhs\n• Annual turnover > ₹2 crores\n• Timeline: Within 6 months of crossing either threshold\n\nConversion process:\n1. Pass board resolution\n2. Appoint minimum 2 directors and 2 shareholders\n3. Alter MOA and AOA\n4. File Form INC-6 with ROC\n5. ROC issues fresh Certificate of Incorporation\n\nVoluntary conversion is also allowed anytime without crossing thresholds.`,
    relatedIds: ["opc-1", "pvt-1", "opc-4"],
    serviceLink: "/services",
    serviceName: "OPC to Pvt Ltd Conversion",
    tags: ["conversion", "threshold", "turnover"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "opc-3",
    category: "opc",
    question: "Can an OPC have employees and hire staff?",
    bluf: "Yes, an OPC can hire unlimited employees. It has the same legal standing as a Pvt Ltd for employment contracts, PF/ESI registration, and payroll compliance.",
    detail: `OPC employment capabilities:\n• Can hire unlimited employees\n• Must register for EPF if 20+ employees\n• Must register for ESI if 10+ employees\n• Can issue appointment letters and employment contracts\n• TDS on salary (Section 192) applies normally\n• Professional tax registration required in applicable states\n\nThe "one person" refers only to ownership (single shareholder), not operational capacity.`,
    relatedIds: ["opc-1", "opc-4", "gst-2"],
    serviceLink: "/services",
    serviceName: "OPC Registration",
    tags: ["employees", "hiring", "EPF", "ESI"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "opc-4",
    category: "opc",
    question: "What are the annual compliance requirements for an OPC?",
    bluf: "OPC must file annual returns (MGT-7A), financial statements (AOC-4), income tax return, and Director KYC (DIR-3). Board meetings are required at least twice a year.",
    detail: `Annual OPC compliances:\n• Form AOC-4: Financial statements (within 180 days of FY end)\n• Form MGT-7A: Simplified annual return (within 60 days of AGM)\n• Income Tax Return: By July 31 (non-audit) or October 31 (audit)\n• DIR-3 KYC: Director verification by September 30\n• Board Meetings: Minimum 2 per year (gap ≤ 90 days between meetings)\n\nExemptions for OPC:\n• No requirement to hold AGM\n• Cash flow statement not mandatory\n• Simplified financial reporting`,
    relatedIds: ["opc-2", "roc-1", "roc-2"],
    serviceLink: "/services",
    serviceName: "OPC Compliance Package",
    tags: ["compliance", "filings", "annual return"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "opc-5",
    category: "opc",
    question: "Who can be a nominee director in an OPC?",
    bluf: "Any Indian citizen with a valid PAN and Aadhaar can be a nominee. The nominee becomes the sole member/director if the original member becomes incapacitated or dies.",
    detail: `Nominee requirements:\n• Must be an Indian citizen\n• Must have valid PAN and Aadhaar\n• Must sign Form INC-3 (consent letter)\n• Cannot be a minor\n• Can be a family member, friend, or professional\n\nNominee's role:\n• Takes over ownership if original member dies/incapacitated\n• Has no active role during normal operations\n• Can be changed anytime by filing Form INC-4\n• Does NOT need to be a director during normal operations\n\nThe nominee is essentially a succession safety net.`,
    relatedIds: ["opc-1", "opc-3", "pvt-4"],
    serviceLink: "/services",
    serviceName: "OPC Registration",
    tags: ["nominee", "succession", "Form INC-3"],
    lastUpdated: "2026-05-31",
  },
  // ═══ SECTION 8 NGO (4) ═══
  {
    id: "s8-1",
    category: "section8",
    question: "What is a Section 8 Company and how is it different from a Trust?",
    bluf: "A Section 8 Company is a non-profit registered under the Companies Act with limited liability. Unlike a Trust, it has a formal corporate structure, mandatory audits, and higher credibility for CSR funding.",
    detail: `Key differences:\n\n• Section 8 Company: Registered under Companies Act 2013, governed by ROC, mandatory annual filings, can receive CSR funds directly, higher credibility with corporates and government.\n\n• Trust: Registered under Indian Trusts Act 1882, governed by Charity Commissioner, simpler compliance, but less credibility for institutional funding.\n\n• Society: Registered under Societies Registration Act 1860, requires minimum 7 members, state-level registration.\n\nSection 8 is recommended for: Education, healthcare, environment, sports, art, science, and social welfare organizations seeking institutional funding.`,
    relatedIds: ["s8-2", "s8-3", "s8-4"],
    serviceLink: "/services",
    serviceName: "Section 8 Registration",
    tags: ["NGO", "non-profit", "Trust", "Society"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "s8-2",
    category: "section8",
    question: "Can a Section 8 Company receive donations and CSR funds?",
    bluf: "Yes. With 12A and 80G registration, donors get tax deductions. Section 8 companies are eligible to receive CSR funds from corporates under Section 135 of the Companies Act.",
    detail: `Funding eligibility:\n• 12A Registration: Exempts the NGO's income from tax\n• 80G Registration: Donors get 50% or 100% tax deduction\n• CSR Funding: Eligible under Schedule VII activities\n• FCRA Registration: Required for receiving foreign donations\n\nTimeline for registrations:\n• 12A & 80G: Apply within 6 months of incorporation\n• FCRA: Apply after 3 years of operations (or prior permission route)\n\nSection 8 companies cannot distribute profits to members — all surplus must be used for charitable objectives.`,
    relatedIds: ["s8-1", "s8-3", "gst-1"],
    serviceLink: "/services",
    serviceName: "12A & 80G Registration",
    tags: ["donations", "CSR", "12A", "80G", "FCRA"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "s8-3",
    category: "section8",
    question: "What is the process to register a Section 8 Company?",
    bluf: "File INC-12 for license, then SPICe+ for incorporation. Requires minimum 2 directors, charitable objectives in MOA, and central government license approval (15-20 days).",
    detail: `Registration steps:\n1. Obtain DSC and DIN for directors\n2. Apply for name via RUN/SPICe+ Part A\n3. File Form INC-12 (License Application) with:\n   • MOA with charitable objectives\n   • Estimated 3-year financial projections\n   • Declaration of directors\n4. Central Government grants license\n5. File SPICe+ Part B for incorporation\n6. ROC issues Certificate of Incorporation\n\nTimeline: 15-20 working days\nCost: ₹2,499 (Incroute professional fee) + government charges`,
    relatedIds: ["s8-1", "s8-2", "s8-4"],
    serviceLink: "/services",
    serviceName: "Section 8 Registration",
    tags: ["registration", "INC-12", "license"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "s8-4",
    category: "section8",
    question: "What are the compliance requirements for a Section 8 Company?",
    bluf: "Same as Pvt Ltd: annual ROC filings (AOC-4, MGT-7), board meetings, statutory audit, plus additional requirements like maintaining accounts showing charitable spending.",
    detail: `Annual compliances:\n• Form AOC-4: Financial statements\n• Form MGT-7: Annual return\n• Statutory Audit: Mandatory every year\n• Board Meetings: Minimum 4 per year\n• AGM: Within 6 months of FY end\n• Income Tax Return: ITR-7\n• 12A/80G renewal (if applicable)\n\nAdditional requirements:\n• Maintain separate books showing charitable expenditure\n• Cannot pay dividends or distribute profits\n• Cannot alter objectives without central government approval\n• Must spend minimum 85% of income on charitable activities`,
    relatedIds: ["s8-1", "roc-1", "roc-2"],
    serviceLink: "/services",
    serviceName: "NGO Compliance Package",
    tags: ["compliance", "audit", "filings"],
    lastUpdated: "2026-05-31",
  },
  // ═══ GST & TAX (5) ═══
  {
    id: "gst-1",
    category: "gst-tax",
    question: "When is GST registration mandatory for a company?",
    bluf: "GST registration is mandatory if annual turnover exceeds ₹40 lakhs (₹20 lakhs for services/special category states) or if you sell inter-state.",
    detail: `Mandatory GST registration triggers:\n• Aggregate turnover > ₹40 lakhs (goods) or ₹20 lakhs (services)\n• Inter-state supply of goods/services (any amount)\n• E-commerce operators/sellers\n• Casual taxable persons\n• Non-resident taxable persons\n• Agents of suppliers\n• Input Service Distributors\n\nVoluntary registration is allowed below thresholds (recommended for B2B businesses to claim Input Tax Credit).\n\nTimeline: 3-5 working days for GSTIN activation.`,
    relatedIds: ["gst-2", "gst-3", "gst-5"],
    serviceLink: "/services",
    serviceName: "GST Registration",
    tags: ["GST", "turnover", "threshold", "registration"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "gst-2",
    category: "gst-tax",
    question: "What is Input Tax Credit (ITC) and how does it work?",
    bluf: "ITC allows you to reduce GST payable by claiming credit for GST already paid on business purchases. Net tax = Output GST - Input GST.",
    detail: `How ITC works:\n• You pay GST on purchases (inputs) → This is your Input Tax\n• You collect GST on sales (outputs) → This is your Output Tax\n• Net GST payable = Output Tax - Input Tax Credit\n\nConditions for claiming ITC:\n• Must have valid tax invoice\n• Goods/services must be used for business\n• Supplier must have filed their GSTR-1\n• Must be reflected in your GSTR-2B\n• Payment to supplier within 180 days\n\nBlocked ITC: Food, personal vehicles, membership clubs, beauty treatments.`,
    relatedIds: ["gst-1", "gst-3", "gst-4"],
    serviceLink: "/services",
    serviceName: "GST Filing Services",
    tags: ["ITC", "input tax", "credit", "GSTR"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "gst-3",
    category: "gst-tax",
    question: "What are the monthly/quarterly GST filing requirements?",
    bluf: "Regular taxpayers file GSTR-1 (sales) by 11th and GSTR-3B (summary + payment) by 20th monthly. Small taxpayers can opt for quarterly filing under QRMP scheme.",
    detail: `Filing schedule:\n\nMonthly (turnover > ₹5 Cr):\n• GSTR-1: Outward supplies — by 11th of next month\n• GSTR-3B: Summary return + tax payment — by 20th\n\nQuarterly (QRMP scheme, turnover < ₹5 Cr):\n• GSTR-1: Quarterly (by 13th of month after quarter)\n• GSTR-3B: Quarterly\n• IFF: Optional monthly invoice furnishing\n\nAnnual:\n• GSTR-9: Annual return — by December 31\n• GSTR-9C: Reconciliation (if turnover > ₹5 Cr)\n\nPenalty for late filing: ₹50/day (₹20/day for nil returns), max ₹10,000.`,
    relatedIds: ["gst-1", "gst-2", "gst-4"],
    serviceLink: "/services",
    serviceName: "GST Return Filing",
    tags: ["GSTR-1", "GSTR-3B", "filing", "returns"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "gst-4",
    category: "gst-tax",
    question: "What is the TDS requirement for companies?",
    bluf: "Companies must deduct TDS on payments exceeding specified limits (e.g., ₹30,000 for contractors, ₹40,000 for rent). TDS returns are filed quarterly via Form 24Q/26Q.",
    detail: `Key TDS sections:\n• Section 194C: Contractors — 1% (individual) / 2% (others) above ₹30,000\n• Section 194J: Professional fees — 10% above ₹30,000\n• Section 194I: Rent — 10% above ₹2,40,000/year\n• Section 194H: Commission — 5% above ₹15,000\n• Section 192: Salary — as per slab rates\n\nFiling:\n• Form 24Q: Salary TDS (quarterly)\n• Form 26Q: Non-salary TDS (quarterly)\n• Due dates: July 31, Oct 31, Jan 31, May 31\n\nTAN (Tax Deduction Account Number) is mandatory for TDS deduction.`,
    relatedIds: ["gst-3", "gst-5", "roc-3"],
    serviceLink: "/services",
    serviceName: "TDS Filing Services",
    tags: ["TDS", "tax deduction", "Form 26Q", "TAN"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "gst-5",
    category: "gst-tax",
    question: "What tax benefits are available under Startup India?",
    bluf: "DPIIT-recognized startups get 3-year tax holiday (Section 80-IAC), angel tax exemption (Section 56), and self-certification for labor/environment laws.",
    detail: `Startup India benefits:\n\n1. Tax Holiday (Section 80-IAC):\n   • 100% tax exemption for 3 consecutive years out of first 10 years\n   • Must be incorporated after April 1, 2016\n   • Turnover < ₹100 Cr in the relevant year\n\n2. Angel Tax Exemption (Section 56(2)(viib)):\n   • Exemption from tax on share premium received from investors\n   • Must be DPIIT recognized\n\n3. Self-Certification:\n   • No inspections for 3 years under 6 labor laws and 3 environment laws\n\n4. Fast-track Patent/Trademark:\n   • 80% rebate on patent filing fees\n   • 50% rebate on trademark filing fees\n\nEligibility: Must be < 10 years old, turnover < ₹100 Cr, working on innovation.`,
    relatedIds: ["gst-1", "pvt-1", "trademark-1"],
    serviceLink: "/services",
    serviceName: "Startup India Registration",
    tags: ["Startup India", "DPIIT", "tax holiday", "80-IAC"],
    lastUpdated: "2026-05-31",
  },
  // ═══ ROC COMPLIANCE (4) ═══
  {
    id: "roc-1",
    category: "roc",
    question: "What happens if I miss annual ROC filings?",
    bluf: "Late filing attracts ₹100/day penalty per form (no cap). Missing 2+ consecutive years can lead to company strike-off and director disqualification (DIN deactivation).",
    detail: `Consequences of non-compliance:\n\n1. Financial Penalties:\n   • AOC-4 late: ₹100/day (no maximum cap)\n   • MGT-7 late: ₹100/day (no maximum cap)\n   • Penalties apply to BOTH the company and every officer in default\n\n2. Strike-Off (Section 248):\n   • ROC can strike off company name if no filings for 2+ years\n   • Directors get disqualified under Section 164(2)\n   • DIN gets deactivated — cannot be director in ANY company for 5 years\n\n3. Revival:\n   • Must apply to NCLT (National Company Law Tribunal)\n   • Costs ₹50,000–₹2,00,000 in legal fees\n   • Takes 6-12 months\n\nPrevention: Use Incroute's compliance calendar to never miss a deadline.`,
    relatedIds: ["roc-2", "roc-3", "llp-4"],
    serviceLink: "/services",
    serviceName: "Annual Compliance Package",
    tags: ["penalty", "strike-off", "disqualification", "DIN"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "roc-2",
    category: "roc",
    question: "What is DIR-3 KYC and who needs to file it?",
    bluf: "DIR-3 KYC is an annual verification of director identity. Every person holding a DIN must file it by September 30 each year, or their DIN gets deactivated.",
    detail: `DIR-3 KYC details:\n• Who: Every person with an allotted DIN (active or inactive)\n• When: By September 30 every year\n• First time: File web-form DIR-3 KYC (with OTP verification)\n• Subsequent years: File DIR-3 KYC-WEB (simplified)\n\nPenalty for non-filing:\n• DIN marked as "Deactivated"\n• Cannot sign any ROC forms\n• Reactivation fee: ₹5,000\n• Must file pending KYC + pay penalty to reactivate\n\nRequired details: PAN, Aadhaar, mobile, email, current address, passport (if applicable).`,
    relatedIds: ["roc-1", "roc-3", "pvt-4"],
    serviceLink: "/services",
    serviceName: "DIR-3 KYC Filing",
    tags: ["DIR-3", "KYC", "DIN", "annual"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "roc-3",
    category: "roc",
    question: "What is Form AOC-4 and when must it be filed?",
    bluf: "Form AOC-4 is the annual filing of audited financial statements (balance sheet, P&L, cash flow) with ROC. Due within 30 days of the AGM.",
    detail: `AOC-4 details:\n• What: Audited financial statements of the company\n• Contents: Balance sheet, P&L statement, cash flow, notes to accounts, auditor's report\n• Due date: Within 30 days of AGM (AGM must be held within 6 months of FY end)\n• Effective deadline: Usually by November 30 for March FY companies\n\nAttachments required:\n• Board's report\n• Auditor's report\n• CSR report (if applicable)\n• Related party transactions\n\nPenalty: ₹100/day for company + ₹100/day for every officer in default.`,
    relatedIds: ["roc-1", "roc-2", "roc-4"],
    serviceLink: "/services",
    serviceName: "ROC Filing Services",
    tags: ["AOC-4", "financial statements", "audit", "AGM"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "roc-4",
    category: "roc",
    question: "How to change the registered office address of a company?",
    bluf: "File Form INC-22 with ROC along with new address proof, NOC from new landlord, and board resolution. If changing state, additional NCLT approval is needed.",
    detail: `Address change scenarios:\n\n1. Within same city (same ROC jurisdiction):\n   • Board resolution + Form INC-22\n   • New utility bill + NOC\n   • Timeline: 7-10 days\n\n2. Within same state (different ROC):\n   • Special resolution (shareholders)\n   • Form INC-23 + INC-22\n   • Timeline: 15-20 days\n\n3. Different state:\n   • Special resolution\n   • NCLT petition required\n   • Form INC-23 + MGT-14 + INC-22\n   • Timeline: 2-3 months\n\nAll changes must be updated in MOA and intimated to GST, banks, and other registrations.`,
    relatedIds: ["roc-1", "roc-3", "pvt-3"],
    serviceLink: "/services",
    serviceName: "Address Change Filing",
    tags: ["address", "INC-22", "registered office"],
    lastUpdated: "2026-05-31",
  },
  // ═══ TRADEMARK (3) ═══
  {
    id: "trademark-1",
    category: "trademark",
    question: "How long does trademark registration take in India?",
    bluf: "Trademark registration takes 12-18 months for final certificate. However, you get TM™ status immediately upon filing and can use it from day one.",
    detail: `Trademark timeline:\n\n1. Filing & TM™ Status: Day 1 (immediate)\n2. Vienna Codification: 1-2 days\n3. Examination Report: 30-60 days\n4. Publication in Journal: After examination clearance\n5. Opposition Period: 4 months from publication\n6. Registration Certificate: If no opposition\n\nTotal: 12-18 months for ® status\n\nYou can use ™ immediately after filing. The ® symbol can only be used after final registration.\n\nFiling fee: ₹4,500 (online, for startups/individuals) or ₹9,000 (others).`,
    relatedIds: ["trademark-2", "trademark-3", "gst-5"],
    serviceLink: "/services",
    serviceName: "Trademark Registration",
    tags: ["trademark", "brand", "IP", "registration"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "trademark-2",
    category: "trademark",
    question: "What can be trademarked in India?",
    bluf: "You can trademark: brand names, logos, slogans, sounds, colors, shapes, and even smells. It must be distinctive and not descriptive of the goods/services.",
    detail: `Registrable trademarks:\n• Word marks (brand names like "Incroute")\n• Device marks (logos, symbols)\n• Combined marks (name + logo together)\n• Sound marks (jingles, tunes)\n• Color combinations\n• 3D shapes (product packaging)\n• Certification marks\n• Collective marks\n\nNot registrable:\n• Generic/descriptive words ("Best Software")\n• Deceptive marks\n• Marks identical to existing registered marks\n• National emblems, flags\n• Scandalous or offensive marks\n\nTip: Coined/invented words get strongest protection (e.g., "Google", "Xerox").`,
    relatedIds: ["trademark-1", "trademark-3", "pvt-1"],
    serviceLink: "/services",
    serviceName: "Trademark Search & Filing",
    tags: ["trademark", "logo", "brand protection"],
    lastUpdated: "2026-05-31",
  },
  {
    id: "trademark-3",
    category: "trademark",
    question: "What is the difference between ™ and ® symbols?",
    bluf: "™ means you've claimed the mark (can use immediately after filing). ® means officially registered by the Trademark Registry (only after final certificate, 12-18 months).",
    detail: `Symbol meanings:\n\n™ (Trademark):\n• Can be used immediately after filing application\n• Indicates you're claiming rights over the mark\n• No legal penalty for using without registration\n• Provides common law protection\n\n® (Registered):\n• Can ONLY be used after receiving registration certificate\n• Using ® without registration is a criminal offense (Section 107)\n• Provides statutory protection under Trademarks Act 1999\n• Enables you to sue for infringement with stronger legal standing\n\nSM℠ (Service Mark): Same as ™ but specifically for services (less common in India).`,
    relatedIds: ["trademark-1", "trademark-2", "pvt-1"],
    serviceLink: "/services",
    serviceName: "Trademark Registration",
    tags: ["trademark", "symbols", "registration", "IP"],
    lastUpdated: "2026-05-31",
  },
];
