-- INCroute Books MVP foundation
-- MySQL 8+, forward-only and safe to re-run.
-- Existing INCroute service-billing tables are intentionally unchanged.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `BooksPermission` (
  `id` VARCHAR(30) NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `module` VARCHAR(50) NOT NULL,
  `action` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksPermission_code_key` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksTenant` (
  `id` VARCHAR(30) NOT NULL,
  `clientId` VARCHAR(30) NULL,
  `ownerUserId` VARCHAR(191) NULL,
  `name` VARCHAR(191) NOT NULL,
  `status` ENUM('ACTIVE','SUSPENDED','CLOSED') NOT NULL DEFAULT 'ACTIVE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksTenant_clientId_idx` (`clientId`),
  UNIQUE KEY `BooksTenant_ownerUserId_key` (`ownerUserId`),
  CONSTRAINT `BooksTenant_single_owner_chk` CHECK (`clientId` IS NULL OR `ownerUserId` IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksOrganisation` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `sourceEntityId` VARCHAR(30) NULL,
  `legalName` VARCHAR(191) NOT NULL,
  `tradeName` VARCHAR(191) NULL,
  `entityType` ENUM('PRIVATE_LIMITED','PUBLIC_LIMITED','LLP','OPC','PARTNERSHIP','PROPRIETORSHIP','SECTION_8','OTHER') NOT NULL,
  `pan` VARCHAR(10) NULL,
  `tan` VARCHAR(10) NULL,
  `cinLlpIn` VARCHAR(30) NULL,
  `baseCurrency` CHAR(3) NOT NULL DEFAULT 'INR',
  `reportingMethod` ENUM('ACCRUAL','CASH') NOT NULL DEFAULT 'ACCRUAL',
  `financialYearStartMonth` TINYINT UNSIGNED NOT NULL DEFAULT 4,
  `invoicePrefix` VARCHAR(20) NOT NULL DEFAULT 'INV',
  `nextInvoiceNumber` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `registeredAddress` JSON NULL,
  `status` ENUM('ACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksOrganisation_tenant_legal_key` (`tenantId`,`legalName`),
  KEY `BooksOrganisation_tenant_idx` (`tenantId`,`status`),
  CONSTRAINT `BooksOrganisation_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksRole` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(60) NOT NULL,
  `isSystem` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksRole_org_code_key` (`tenantId`,`organisationId`,`code`),
  KEY `BooksRole_scope_idx` (`tenantId`,`organisationId`),
  CONSTRAINT `BooksRole_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksRole_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksRolePermission` (
  `roleId` VARCHAR(30) NOT NULL,
  `permissionId` VARCHAR(30) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`roleId`,`permissionId`),
  CONSTRAINT `BooksRolePermission_role_fk` FOREIGN KEY (`roleId`) REFERENCES `BooksRole` (`id`),
  CONSTRAINT `BooksRolePermission_permission_fk` FOREIGN KEY (`permissionId`) REFERENCES `BooksPermission` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksOrganisationMember` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `roleId` VARCHAR(30) NOT NULL,
  `status` ENUM('INVITED','ACTIVE','SUSPENDED','REMOVED') NOT NULL DEFAULT 'ACTIVE',
  `joinedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksOrganisationMember_user_org_key` (`userId`,`organisationId`),
  KEY `BooksOrganisationMember_scope_idx` (`tenantId`,`organisationId`,`userId`,`status`),
  CONSTRAINT `BooksOrganisationMember_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksOrganisationMember_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksOrganisationMember_role_fk` FOREIGN KEY (`roleId`) REFERENCES `BooksRole` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksBranch` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `code` VARCHAR(30) NOT NULL,
  `stateCode` CHAR(2) NULL,
  `address` JSON NULL,
  `isHeadOffice` TINYINT(1) NOT NULL DEFAULT 0,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksBranch_org_code_key` (`tenantId`,`organisationId`,`code`),
  KEY `BooksBranch_scope_idx` (`tenantId`,`organisationId`,`isActive`),
  CONSTRAINT `BooksBranch_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksBranch_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksGSTRegistration` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `branchId` VARCHAR(30) NOT NULL,
  `gstin` CHAR(15) NOT NULL,
  `legalName` VARCHAR(191) NOT NULL,
  `tradeName` VARCHAR(191) NULL,
  `stateCode` CHAR(2) NOT NULL,
  `registrationType` ENUM('REGULAR','COMPOSITION','CASUAL','SEZ','UNREGISTERED') NOT NULL DEFAULT 'REGULAR',
  `effectiveFrom` DATE NULL,
  `isDefault` TINYINT(1) NOT NULL DEFAULT 0,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksGSTRegistration_gstin_key` (`tenantId`,`organisationId`,`gstin`),
  KEY `BooksGSTRegistration_scope_idx` (`tenantId`,`organisationId`,`isActive`),
  CONSTRAINT `BooksGSTRegistration_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksGSTRegistration_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksGSTRegistration_branch_fk` FOREIGN KEY (`branchId`) REFERENCES `BooksBranch` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksFiscalYear` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `label` VARCHAR(20) NOT NULL,
  `startsOn` DATE NOT NULL,
  `endsOn` DATE NOT NULL,
  `isCurrent` TINYINT(1) NOT NULL DEFAULT 0,
  `isClosed` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksFiscalYear_org_label_key` (`tenantId`,`organisationId`,`label`),
  KEY `BooksFiscalYear_scope_idx` (`tenantId`,`organisationId`,`startsOn`,`endsOn`),
  CONSTRAINT `BooksFiscalYear_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksFiscalYear_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksAccountingPeriod` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `fiscalYearId` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `startsOn` DATE NOT NULL,
  `endsOn` DATE NOT NULL,
  `status` ENUM('OPEN','SOFT_LOCKED','LOCKED') NOT NULL DEFAULT 'OPEN',
  `lockedAt` DATETIME(3) NULL,
  `lockedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksAccountingPeriod_org_range_key` (`tenantId`,`organisationId`,`startsOn`,`endsOn`),
  KEY `BooksAccountingPeriod_scope_idx` (`tenantId`,`organisationId`,`status`,`startsOn`,`endsOn`),
  CONSTRAINT `BooksAccountingPeriod_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksAccountingPeriod_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksAccountingPeriod_fy_fk` FOREIGN KEY (`fiscalYearId`) REFERENCES `BooksFiscalYear` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksContact` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `type` ENUM('CUSTOMER','VENDOR','BOTH') NOT NULL,
  `displayName` VARCHAR(191) NOT NULL,
  `legalName` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `phone` VARCHAR(30) NULL,
  `gstin` CHAR(15) NULL,
  `pan` CHAR(10) NULL,
  `placeOfSupply` CHAR(2) NULL,
  `paymentTermsDays` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `openingBalance` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `notes` TEXT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksContact_scope_type_idx` (`tenantId`,`organisationId`,`type`,`isActive`),
  KEY `BooksContact_scope_name_idx` (`tenantId`,`organisationId`,`displayName`),
  CONSTRAINT `BooksContact_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksContact_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksAddress` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `contactId` VARCHAR(30) NOT NULL,
  `type` ENUM('BILLING','SHIPPING','REGISTERED','OTHER') NOT NULL,
  `line1` VARCHAR(191) NOT NULL,
  `line2` VARCHAR(191) NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `stateCode` CHAR(2) NOT NULL,
  `postalCode` VARCHAR(10) NOT NULL,
  `countryCode` CHAR(2) NOT NULL DEFAULT 'IN',
  `isDefault` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksAddress_scope_contact_idx` (`tenantId`,`organisationId`,`contactId`),
  CONSTRAINT `BooksAddress_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksAddress_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksAddress_contact_fk` FOREIGN KEY (`contactId`) REFERENCES `BooksContact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksUnit` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksUnit_org_code_key` (`tenantId`,`organisationId`,`code`),
  KEY `BooksUnit_scope_idx` (`tenantId`,`organisationId`,`isActive`),
  CONSTRAINT `BooksUnit_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksUnit_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksTaxRate` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `rate` DECIMAL(7,4) NOT NULL,
  `taxType` ENUM('GST','CESS','EXEMPT','NON_GST') NOT NULL DEFAULT 'GST',
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksTaxRate_org_name_key` (`tenantId`,`organisationId`,`name`),
  KEY `BooksTaxRate_scope_idx` (`tenantId`,`organisationId`,`isActive`),
  CONSTRAINT `BooksTaxRate_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksTaxRate_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksItem` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `type` ENUM('GOODS','SERVICE') NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `sku` VARCHAR(100) NULL,
  `hsnSac` VARCHAR(20) NOT NULL,
  `unitId` VARCHAR(30) NOT NULL,
  `taxRateId` VARCHAR(30) NULL,
  `sellingPrice` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `purchasePrice` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `openingStock` DECIMAL(18,3) NOT NULL DEFAULT 0.000,
  `reorderPoint` DECIMAL(18,3) NULL,
  `imageDocumentId` VARCHAR(30) NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksItem_org_sku_key` (`tenantId`,`organisationId`,`sku`),
  KEY `BooksItem_scope_idx` (`tenantId`,`organisationId`,`type`,`isActive`),
  CONSTRAINT `BooksItem_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksItem_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksItem_unit_fk` FOREIGN KEY (`unitId`) REFERENCES `BooksUnit` (`id`),
  CONSTRAINT `BooksItem_tax_fk` FOREIGN KEY (`taxRateId`) REFERENCES `BooksTaxRate` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksAccount` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `type` ENUM('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE') NOT NULL,
  `subType` VARCHAR(60) NOT NULL,
  `parentId` VARCHAR(30) NULL,
  `normalBalance` ENUM('DEBIT','CREDIT') NOT NULL,
  `isSystem` TINYINT(1) NOT NULL DEFAULT 0,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksAccount_org_code_key` (`tenantId`,`organisationId`,`code`),
  KEY `BooksAccount_scope_idx` (`tenantId`,`organisationId`,`type`,`isActive`),
  CONSTRAINT `BooksAccount_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksAccount_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksAccount_parent_fk` FOREIGN KEY (`parentId`) REFERENCES `BooksAccount` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksJournalEntry` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `fiscalYearId` VARCHAR(30) NOT NULL,
  `entryNumber` VARCHAR(60) NOT NULL,
  `entryDate` DATE NOT NULL,
  `sourceType` VARCHAR(40) NOT NULL,
  `sourceId` VARCHAR(30) NOT NULL,
  `narration` VARCHAR(500) NOT NULL,
  `status` ENUM('POSTED','REVERSED') NOT NULL DEFAULT 'POSTED',
  `totalDebit` DECIMAL(18,2) NOT NULL,
  `totalCredit` DECIMAL(18,2) NOT NULL,
  `reversalOfId` VARCHAR(30) NULL,
  `postedBy` VARCHAR(191) NOT NULL,
  `postedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksJournalEntry_source_key` (`tenantId`,`organisationId`,`sourceType`,`sourceId`),
  UNIQUE KEY `BooksJournalEntry_number_key` (`tenantId`,`organisationId`,`entryNumber`),
  KEY `BooksJournalEntry_scope_date_idx` (`tenantId`,`organisationId`,`entryDate`,`status`),
  CONSTRAINT `BooksJournalEntry_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksJournalEntry_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksJournalEntry_fy_fk` FOREIGN KEY (`fiscalYearId`) REFERENCES `BooksFiscalYear` (`id`),
  CONSTRAINT `BooksJournalEntry_reversal_fk` FOREIGN KEY (`reversalOfId`) REFERENCES `BooksJournalEntry` (`id`),
  CONSTRAINT `BooksJournalEntry_balanced_chk` CHECK (`totalDebit` = `totalCredit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksJournalLine` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `journalEntryId` VARCHAR(30) NOT NULL,
  `accountId` VARCHAR(30) NOT NULL,
  `contactId` VARCHAR(30) NULL,
  `description` VARCHAR(500) NULL,
  `debit` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `credit` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksJournalLine_scope_entry_idx` (`tenantId`,`organisationId`,`journalEntryId`),
  KEY `BooksJournalLine_scope_account_idx` (`tenantId`,`organisationId`,`accountId`),
  CONSTRAINT `BooksJournalLine_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksJournalLine_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksJournalLine_entry_fk` FOREIGN KEY (`journalEntryId`) REFERENCES `BooksJournalEntry` (`id`),
  CONSTRAINT `BooksJournalLine_account_fk` FOREIGN KEY (`accountId`) REFERENCES `BooksAccount` (`id`),
  CONSTRAINT `BooksJournalLine_contact_fk` FOREIGN KEY (`contactId`) REFERENCES `BooksContact` (`id`),
  CONSTRAINT `BooksJournalLine_side_chk` CHECK ((`debit` > 0 AND `credit` = 0) OR (`credit` > 0 AND `debit` = 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksEstimate` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `customerId` VARCHAR(30) NOT NULL,
  `estimateNumber` VARCHAR(60) NOT NULL,
  `estimateDate` DATE NOT NULL,
  `expiryDate` DATE NULL,
  `status` ENUM('DRAFT','SENT','ACCEPTED','DECLINED','EXPIRED','CONVERTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `subTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `taxTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `grandTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksEstimate_number_key` (`tenantId`,`organisationId`,`estimateNumber`),
  KEY `BooksEstimate_scope_idx` (`tenantId`,`organisationId`,`customerId`,`status`),
  CONSTRAINT `BooksEstimate_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksEstimate_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksEstimate_customer_fk` FOREIGN KEY (`customerId`) REFERENCES `BooksContact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksInvoice` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `branchId` VARCHAR(30) NOT NULL,
  `customerId` VARCHAR(30) NOT NULL,
  `invoiceNumber` VARCHAR(60) NOT NULL,
  `invoiceDate` DATE NOT NULL,
  `dueDate` DATE NOT NULL,
  `placeOfSupply` CHAR(2) NOT NULL,
  `supplyType` ENUM('DOMESTIC','EXPORT','SEZ_WITH_PAYMENT','SEZ_WITHOUT_PAYMENT') NOT NULL DEFAULT 'DOMESTIC',
  `reverseCharge` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('DRAFT','POSTED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED','VOID') NOT NULL DEFAULT 'DRAFT',
  `subTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `discountTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `cgstTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `sgstTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `igstTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `cessTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `roundOff` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `grandTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `amountPaid` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `balanceDue` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `notes` TEXT NULL,
  `terms` TEXT NULL,
  `postedAt` DATETIME(3) NULL,
  `postedBy` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksInvoice_number_key` (`tenantId`,`organisationId`,`invoiceNumber`),
  KEY `BooksInvoice_scope_status_idx` (`tenantId`,`organisationId`,`status`,`invoiceDate`),
  KEY `BooksInvoice_customer_idx` (`tenantId`,`organisationId`,`customerId`,`dueDate`),
  CONSTRAINT `BooksInvoice_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksInvoice_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksInvoice_branch_fk` FOREIGN KEY (`branchId`) REFERENCES `BooksBranch` (`id`),
  CONSTRAINT `BooksInvoice_customer_fk` FOREIGN KEY (`customerId`) REFERENCES `BooksContact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksInvoiceLine` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `invoiceId` VARCHAR(30) NOT NULL,
  `itemId` VARCHAR(30) NULL,
  `description` VARCHAR(500) NOT NULL,
  `hsnSac` VARCHAR(20) NOT NULL,
  `quantity` DECIMAL(18,3) NOT NULL,
  `unitPrice` DECIMAL(18,2) NOT NULL,
  `discountAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `taxableAmount` DECIMAL(18,2) NOT NULL,
  `gstRate` DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  `cgstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `sgstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `igstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `cessAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `lineTotal` DECIMAL(18,2) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksInvoiceLine_scope_invoice_idx` (`tenantId`,`organisationId`,`invoiceId`),
  CONSTRAINT `BooksInvoiceLine_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksInvoiceLine_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksInvoiceLine_invoice_fk` FOREIGN KEY (`invoiceId`) REFERENCES `BooksInvoice` (`id`),
  CONSTRAINT `BooksInvoiceLine_item_fk` FOREIGN KEY (`itemId`) REFERENCES `BooksItem` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksCreditNote` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `invoiceId` VARCHAR(30) NULL,
  `customerId` VARCHAR(30) NOT NULL,
  `creditNoteNumber` VARCHAR(60) NOT NULL,
  `creditNoteDate` DATE NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `status` ENUM('DRAFT','POSTED','APPLIED','REFUNDED','CANCELLED','VOID') NOT NULL DEFAULT 'DRAFT',
  `taxableTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `taxTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `grandTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksCreditNote_number_key` (`tenantId`,`organisationId`,`creditNoteNumber`),
  KEY `BooksCreditNote_scope_idx` (`tenantId`,`organisationId`,`customerId`,`status`),
  CONSTRAINT `BooksCreditNote_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksCreditNote_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksCreditNote_invoice_fk` FOREIGN KEY (`invoiceId`) REFERENCES `BooksInvoice` (`id`),
  CONSTRAINT `BooksCreditNote_customer_fk` FOREIGN KEY (`customerId`) REFERENCES `BooksContact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksCustomerPayment` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `customerId` VARCHAR(30) NOT NULL,
  `bankAccountId` VARCHAR(30) NULL,
  `paymentNumber` VARCHAR(60) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `paymentMode` ENUM('BANK_TRANSFER','UPI','CARD','CHEQUE','CASH','OTHER') NOT NULL,
  `reference` VARCHAR(191) NULL,
  `status` ENUM('DRAFT','POSTED','REVERSED') NOT NULL DEFAULT 'DRAFT',
  `postedAt` DATETIME(3) NULL,
  `postedBy` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksCustomerPayment_number_key` (`tenantId`,`organisationId`,`paymentNumber`),
  KEY `BooksCustomerPayment_scope_idx` (`tenantId`,`organisationId`,`customerId`,`status`),
  CONSTRAINT `BooksCustomerPayment_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksCustomerPayment_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksCustomerPayment_customer_fk` FOREIGN KEY (`customerId`) REFERENCES `BooksContact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksPaymentAllocation` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `paymentId` VARCHAR(30) NOT NULL,
  `invoiceId` VARCHAR(30) NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksPaymentAllocation_payment_invoice_key` (`paymentId`,`invoiceId`),
  KEY `BooksPaymentAllocation_scope_idx` (`tenantId`,`organisationId`,`invoiceId`),
  CONSTRAINT `BooksPaymentAllocation_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksPaymentAllocation_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksPaymentAllocation_payment_fk` FOREIGN KEY (`paymentId`) REFERENCES `BooksCustomerPayment` (`id`),
  CONSTRAINT `BooksPaymentAllocation_invoice_fk` FOREIGN KEY (`invoiceId`) REFERENCES `BooksInvoice` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksPurchaseOrder` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `vendorId` VARCHAR(30) NOT NULL,
  `purchaseOrderNumber` VARCHAR(60) NOT NULL,
  `orderDate` DATE NOT NULL,
  `expectedDate` DATE NULL,
  `status` ENUM('DRAFT','ISSUED','PARTIALLY_BILLED','BILLED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `subTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `taxTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `grandTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksPurchaseOrder_number_key` (`tenantId`,`organisationId`,`purchaseOrderNumber`),
  KEY `BooksPurchaseOrder_scope_idx` (`tenantId`,`organisationId`,`vendorId`,`status`),
  CONSTRAINT `BooksPurchaseOrder_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksPurchaseOrder_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksPurchaseOrder_vendor_fk` FOREIGN KEY (`vendorId`) REFERENCES `BooksContact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksBill` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `vendorId` VARCHAR(30) NOT NULL,
  `billNumber` VARCHAR(100) NOT NULL,
  `billDate` DATE NOT NULL,
  `dueDate` DATE NOT NULL,
  `status` ENUM('DRAFT','POSTED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED','VOID') NOT NULL DEFAULT 'DRAFT',
  `subTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `inputCgst` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `inputSgst` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `inputIgst` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `grandTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `amountPaid` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `balanceDue` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `approvalStatus` ENUM('NOT_REQUIRED','PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'NOT_REQUIRED',
  `postedAt` DATETIME(3) NULL,
  `postedBy` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksBill_vendor_number_key` (`tenantId`,`organisationId`,`vendorId`,`billNumber`),
  KEY `BooksBill_scope_idx` (`tenantId`,`organisationId`,`status`,`billDate`),
  CONSTRAINT `BooksBill_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksBill_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksBill_vendor_fk` FOREIGN KEY (`vendorId`) REFERENCES `BooksContact` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksBillLine` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `billId` VARCHAR(30) NOT NULL,
  `itemId` VARCHAR(30) NULL,
  `expenseAccountId` VARCHAR(30) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `hsnSac` VARCHAR(20) NULL,
  `quantity` DECIMAL(18,3) NOT NULL,
  `unitPrice` DECIMAL(18,2) NOT NULL,
  `taxableAmount` DECIMAL(18,2) NOT NULL,
  `gstRate` DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  `cgstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `sgstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `igstAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `lineTotal` DECIMAL(18,2) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksBillLine_scope_bill_idx` (`tenantId`,`organisationId`,`billId`),
  CONSTRAINT `BooksBillLine_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksBillLine_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksBillLine_bill_fk` FOREIGN KEY (`billId`) REFERENCES `BooksBill` (`id`),
  CONSTRAINT `BooksBillLine_item_fk` FOREIGN KEY (`itemId`) REFERENCES `BooksItem` (`id`),
  CONSTRAINT `BooksBillLine_expense_fk` FOREIGN KEY (`expenseAccountId`) REFERENCES `BooksAccount` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksBankAccount` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `ledgerAccountId` VARCHAR(30) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `bankName` VARCHAR(191) NULL,
  `accountNumberMasked` VARCHAR(30) NULL,
  `ifsc` VARCHAR(20) NULL,
  `type` ENUM('CURRENT','SAVINGS','CASH','CREDIT_CARD','OD','OTHER') NOT NULL,
  `openingBalance` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksBankAccount_scope_idx` (`tenantId`,`organisationId`,`isActive`),
  CONSTRAINT `BooksBankAccount_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksBankAccount_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksBankAccount_ledger_fk` FOREIGN KEY (`ledgerAccountId`) REFERENCES `BooksAccount` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksVendorPayment` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `vendorId` VARCHAR(30) NOT NULL,
  `bankAccountId` VARCHAR(30) NOT NULL,
  `paymentNumber` VARCHAR(60) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `paymentMode` ENUM('BANK_TRANSFER','UPI','CARD','CHEQUE','CASH','OTHER') NOT NULL,
  `reference` VARCHAR(191) NULL,
  `status` ENUM('DRAFT','POSTED','REVERSED') NOT NULL DEFAULT 'DRAFT',
  `postedAt` DATETIME(3) NULL,
  `postedBy` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksVendorPayment_number_key` (`tenantId`,`organisationId`,`paymentNumber`),
  KEY `BooksVendorPayment_scope_idx` (`tenantId`,`organisationId`,`vendorId`,`status`),
  CONSTRAINT `BooksVendorPayment_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksVendorPayment_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksVendorPayment_vendor_fk` FOREIGN KEY (`vendorId`) REFERENCES `BooksContact` (`id`),
  CONSTRAINT `BooksVendorPayment_bank_fk` FOREIGN KEY (`bankAccountId`) REFERENCES `BooksBankAccount` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksExpense` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `vendorId` VARCHAR(30) NULL,
  `expenseAccountId` VARCHAR(30) NOT NULL,
  `paidThroughAccountId` VARCHAR(30) NOT NULL,
  `expenseDate` DATE NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `taxAmount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `status` ENUM('DRAFT','POSTED','REVERSED','VOID') NOT NULL DEFAULT 'DRAFT',
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksExpense_scope_idx` (`tenantId`,`organisationId`,`expenseDate`,`status`),
  CONSTRAINT `BooksExpense_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksExpense_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksExpense_vendor_fk` FOREIGN KEY (`vendorId`) REFERENCES `BooksContact` (`id`),
  CONSTRAINT `BooksExpense_expense_account_fk` FOREIGN KEY (`expenseAccountId`) REFERENCES `BooksAccount` (`id`),
  CONSTRAINT `BooksExpense_paid_account_fk` FOREIGN KEY (`paidThroughAccountId`) REFERENCES `BooksAccount` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksBankTransaction` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `bankAccountId` VARCHAR(30) NOT NULL,
  `transactionDate` DATE NOT NULL,
  `valueDate` DATE NULL,
  `description` VARCHAR(500) NOT NULL,
  `reference` VARCHAR(191) NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `direction` ENUM('CREDIT','DEBIT') NOT NULL,
  `status` ENUM('UNMATCHED','MATCHED','EXCLUDED') NOT NULL DEFAULT 'UNMATCHED',
  `matchedSourceType` VARCHAR(40) NULL,
  `matchedSourceId` VARCHAR(30) NULL,
  `importBatch` VARCHAR(60) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksBankTransaction_scope_idx` (`tenantId`,`organisationId`,`bankAccountId`,`status`,`transactionDate`),
  CONSTRAINT `BooksBankTransaction_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksBankTransaction_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksBankTransaction_bank_fk` FOREIGN KEY (`bankAccountId`) REFERENCES `BooksBankAccount` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksReconciliation` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `bankAccountId` VARCHAR(30) NOT NULL,
  `periodStart` DATE NOT NULL,
  `periodEnd` DATE NOT NULL,
  `statementEndingBalance` DECIMAL(18,2) NOT NULL,
  `bookEndingBalance` DECIMAL(18,2) NOT NULL,
  `difference` DECIMAL(18,2) NOT NULL,
  `status` ENUM('DRAFT','COMPLETED','REOPENED') NOT NULL DEFAULT 'DRAFT',
  `completedAt` DATETIME(3) NULL,
  `completedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksReconciliation_scope_idx` (`tenantId`,`organisationId`,`bankAccountId`,`periodEnd`),
  CONSTRAINT `BooksReconciliation_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksReconciliation_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksReconciliation_bank_fk` FOREIGN KEY (`bankAccountId`) REFERENCES `BooksBankAccount` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksInventoryMovement` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `itemId` VARCHAR(30) NOT NULL,
  `branchId` VARCHAR(30) NOT NULL,
  `movementDate` DATE NOT NULL,
  `sourceType` VARCHAR(40) NOT NULL,
  `sourceId` VARCHAR(30) NOT NULL,
  `quantity` DECIMAL(18,3) NOT NULL,
  `unitCost` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksInventoryMovement_source_key` (`tenantId`,`organisationId`,`sourceType`,`sourceId`,`itemId`),
  KEY `BooksInventoryMovement_scope_idx` (`tenantId`,`organisationId`,`itemId`,`movementDate`),
  CONSTRAINT `BooksInventoryMovement_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksInventoryMovement_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksInventoryMovement_item_fk` FOREIGN KEY (`itemId`) REFERENCES `BooksItem` (`id`),
  CONSTRAINT `BooksInventoryMovement_branch_fk` FOREIGN KEY (`branchId`) REFERENCES `BooksBranch` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksDocumentLink` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `documentId` VARCHAR(30) NOT NULL,
  `sourceType` VARCHAR(40) NOT NULL,
  `sourceId` VARCHAR(30) NOT NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 1,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `BooksDocumentLink_document_source_key` (`tenantId`,`organisationId`,`documentId`,`sourceType`,`sourceId`),
  KEY `BooksDocumentLink_scope_idx` (`tenantId`,`organisationId`,`sourceType`,`sourceId`),
  CONSTRAINT `BooksDocumentLink_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksDocumentLink_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksWorkflowRule` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `module` VARCHAR(50) NOT NULL,
  `action` VARCHAR(50) NOT NULL,
  `conditions` JSON NOT NULL,
  `approverRoleId` VARCHAR(30) NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksWorkflowRule_scope_idx` (`tenantId`,`organisationId`,`module`,`isActive`),
  CONSTRAINT `BooksWorkflowRule_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksWorkflowRule_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksWorkflowRule_role_fk` FOREIGN KEY (`approverRoleId`) REFERENCES `BooksRole` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksApproval` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `workflowRuleId` VARCHAR(30) NULL,
  `sourceType` VARCHAR(40) NOT NULL,
  `sourceId` VARCHAR(30) NOT NULL,
  `requestedBy` VARCHAR(191) NOT NULL,
  `assignedTo` VARCHAR(191) NULL,
  `status` ENUM('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `comment` VARCHAR(500) NULL,
  `decidedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksApproval_scope_idx` (`tenantId`,`organisationId`,`sourceType`,`sourceId`,`status`),
  CONSTRAINT `BooksApproval_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksApproval_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`),
  CONSTRAINT `BooksApproval_rule_fk` FOREIGN KEY (`workflowRuleId`) REFERENCES `BooksWorkflowRule` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `BooksAuditLog` (
  `id` VARCHAR(30) NOT NULL,
  `tenantId` VARCHAR(30) NOT NULL,
  `organisationId` VARCHAR(30) NOT NULL,
  `actorUserId` VARCHAR(191) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `entityType` VARCHAR(60) NOT NULL,
  `entityId` VARCHAR(30) NOT NULL,
  `beforeData` JSON NULL,
  `afterData` JSON NULL,
  `ipAddress` VARCHAR(64) NULL,
  `userAgent` VARCHAR(500) NULL,
  `hash` CHAR(64) NOT NULL,
  `previousHash` CHAR(64) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `BooksAuditLog_scope_entity_idx` (`tenantId`,`organisationId`,`entityType`,`entityId`,`createdAt`),
  KEY `BooksAuditLog_scope_actor_idx` (`tenantId`,`organisationId`,`actorUserId`,`createdAt`),
  CONSTRAINT `BooksAuditLog_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `BooksTenant` (`id`),
  CONSTRAINT `BooksAuditLog_org_fk` FOREIGN KEY (`organisationId`) REFERENCES `BooksOrganisation` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
