import React, { useEffect, useState } from "react";
import { CheckCircle2, IndianRupee, Plus, Search, ShoppingCart, Trash2, WalletCards } from "lucide-react";
import { booksApi, indianDate, inr } from "../api";
import type { BooksContact, BooksItem, BooksOrganisation } from "../types";
import { EmptyState, ErrorState, LoadingState, Modal, PageHeader, Status } from "./Common";

interface Bill { id: string; billNumber: string; billDate: string; dueDate: string; status: string; grandTotal: string; balanceDue: string; vendorName: string; vendorGstin?: string }
interface Expense { id: string; expenseDate: string; description: string; amount: string; taxAmount: string; status: string; vendorName?: string }
interface BillLine { itemId: string; description: string; hsnSac: string; quantity: string; unitPrice: string; gstRate: string }
const day = () => new Date().toISOString().slice(0,10);
const blankLine = (): BillLine => ({ itemId: "", description: "", hsnSac: "", quantity: "1", unitPrice: "0.00", gstRate: "18" });

export default function BillsPage({ organisation, onNavigate }:{ organisation: BooksOrganisation; onNavigate: (route: string) => void }) {
  const [bills, setBills] = useState<Bill[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]);
  const [vendors, setVendors] = useState<BooksContact[]>([]); const [items, setItems] = useState<BooksItem[]>([]);
  const [tab, setTab] = useState<"bills"|"expenses">("bills"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  const [showBill, setShowBill] = useState(false); const [showExpense, setShowExpense] = useState(false); const [postTarget, setPostTarget] = useState<Bill|null>(null);
  const [saving, setSaving] = useState(false); const [formError, setFormError] = useState("");
  const [billForm, setBillForm] = useState({ vendorId: "", billNumber: "", billDate: day(), dueDate: day(), placeOfSupply: organisation.gstin?.slice(0,2) || "", lines: [blankLine()] });
  const [expenseForm, setExpenseForm] = useState({ vendorId: "", expenseDate: day(), description: "", amount: "0.00" });
  const load = async () => {
    setLoading(true); setError("");
    try { const [records, contacts, masterItems] = await Promise.all([booksApi<{bills:Bill[];expenses:Expense[]}>(`/bills?organisationId=${organisation.id}`), booksApi<{contacts:BooksContact[]}>(`/contacts?organisationId=${organisation.id}&type=VENDOR`), booksApi<{items:BooksItem[]}>(`/items?organisationId=${organisation.id}`)]); setBills(records.bills); setExpenses(records.expenses); setVendors(contacts.contacts); setItems(masterItems.items); }
    catch (cause:any) { setError(cause.message || "Unable to load purchase records"); } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [organisation.id]);
  const selectVendor = (vendorId:string) => { const vendor=vendors.find((item)=>item.id===vendorId); setBillForm((current)=>({...current,vendorId,placeOfSupply:vendor?.placeOfSupply||current.placeOfSupply})); };
  const updateLine = (index:number, updates:Partial<BillLine>) => setBillForm((current)=>({...current,lines:current.lines.map((line,i)=>i===index?{...line,...updates}:line)}));
  const selectItem = (index:number,itemId:string) => { const item=items.find((entry)=>entry.id===itemId); updateLine(index,item?{itemId,description:item.name,hsnSac:item.hsnSac,unitPrice:String(item.purchasePrice),gstRate:String(item.gstRate||"0")}:{itemId}); };
  const createBill = async (event:React.FormEvent) => { event.preventDefault(); setSaving(true); setFormError(""); try { await booksApi("/bills",{method:"POST",body:JSON.stringify({organisationId:organisation.id,...billForm})}); setShowBill(false); setBillForm({vendorId:"",billNumber:"",billDate:day(),dueDate:day(),placeOfSupply:organisation.gstin?.slice(0,2)||"",lines:[blankLine()]}); await load(); } catch(cause:any){setFormError(cause.message||"Unable to create bill");} finally{setSaving(false);} };
  const postBill = async () => { if(!postTarget)return; setSaving(true); setFormError(""); try{await booksApi(`/bills/${postTarget.id}/post`,{method:"POST",body:JSON.stringify({organisationId:organisation.id})});setPostTarget(null);await load();}catch(cause:any){setFormError(cause.message||"Unable to post bill");}finally{setSaving(false);} };
  const createExpense = async (event:React.FormEvent) => { event.preventDefault();setSaving(true);setFormError("");try{await booksApi("/expenses",{method:"POST",body:JSON.stringify({organisationId:organisation.id,...expenseForm,vendorId:expenseForm.vendorId||null})});setShowExpense(false);setExpenseForm({vendorId:"",expenseDate:day(),description:"",amount:"0.00"});await load();}catch(cause:any){setFormError(cause.message||"Unable to post expense");}finally{setSaving(false);} };
  if(loading)return <LoadingState label="Loading bills and expenses"/>; if(error)return <ErrorState message={error} onRetry={load}/>;
  const shownBills=bills.filter((bill)=>[bill.billNumber,bill.vendorName,bill.status].some((v)=>v.toLowerCase().includes(search.toLowerCase()))); const shownExpenses=expenses.filter((expense)=>[expense.description,expense.vendorName||"",expense.status].some((v)=>v.toLowerCase().includes(search.toLowerCase())));
  return <div className="books-page"><PageHeader eyebrow="Purchases" title="Bills & expenses" description="Record vendor liabilities separately from immediately paid operating expenses." action={<div className="books-header-actions"><button className="books-secondary" onClick={()=>setShowExpense(true)}><WalletCards/>New expense</button><button className="books-primary" onClick={()=>setShowBill(true)}><Plus/>New bill</button></div>}/>
    <div className="books-segmented"><button className={tab==="bills"?"active":""} onClick={()=>setTab("bills")}>Vendor bills <span>{bills.length}</span></button><button className={tab==="expenses"?"active":""} onClick={()=>setTab("expenses")}>Paid expenses <span>{expenses.length}</span></button></div>
    <section className="books-panel books-table-panel"><div className="books-table-toolbar"><div className="books-inline-search"><Search/><input placeholder={`Search ${tab}`} value={search} onChange={(e)=>setSearch(e.target.value)}/></div><span>{tab==="bills"?shownBills.length:shownExpenses.length} records</span></div>
      {tab==="bills" ? (shownBills.length?<div className="books-table-wrap"><table className="books-table"><thead><tr><th>Bill</th><th>Vendor</th><th>Dates</th><th>Status</th><th className="num">Total</th><th className="num">Balance</th><th>Action</th></tr></thead><tbody>{shownBills.map((bill)=><tr key={bill.id}><td><strong className="books-mono">{bill.billNumber}</strong></td><td><strong>{bill.vendorName}</strong><small className="books-cell-sub">{bill.vendorGstin||"Unregistered"}</small></td><td>{indianDate(bill.billDate)}<small className="books-cell-sub">Due {indianDate(bill.dueDate)}</small></td><td><Status value={bill.status}/></td><td className="num"><strong>{inr(bill.grandTotal)}</strong></td><td className="num">{inr(bill.balanceDue)}</td><td><div className="books-row-actions">{bill.status==="DRAFT"&&<button title="Post bill" onClick={()=>{setPostTarget(bill);setFormError("");}}><CheckCircle2/></button>}</div></td></tr>)}</tbody></table></div>:<EmptyState icon={ShoppingCart} title="No vendor bills yet" description="Create a bill draft, review it, then post the payable and input GST." action={<button className="books-primary" onClick={()=>setShowBill(true)}><Plus/>Create first bill</button>}/>) : (shownExpenses.length?<div className="books-table-wrap"><table className="books-table"><thead><tr><th>Date</th><th>Description</th><th>Vendor</th><th>Status</th><th className="num">Amount</th></tr></thead><tbody>{shownExpenses.map((expense)=><tr key={expense.id}><td>{indianDate(expense.expenseDate)}</td><td><strong>{expense.description}</strong></td><td>{expense.vendorName||"Direct expense"}</td><td><Status value={expense.status}/></td><td className="num"><strong>{inr(expense.amount)}</strong></td></tr>)}</tbody></table></div>:<EmptyState icon={WalletCards} title="No paid expenses yet" description="Record an operating expense paid through cash. It posts immediately to the ledger." action={<button className="books-primary" onClick={()=>setShowExpense(true)}>Record expense</button>}/>)}</section>
    {showBill&&<Modal title="Create vendor bill" description="This is saved as a draft until you post it." onClose={()=>setShowBill(false)}><form className="books-modal-form books-invoice-form" onSubmit={createBill}>{!vendors.length?<div className="books-prerequisite"><ShoppingCart/><div><strong>Add a vendor first</strong><p>Vendor identity and place of supply are required.</p></div><button type="button" className="books-secondary" onClick={()=>{setShowBill(false);onNavigate("vendors");}}>Open vendors</button></div>:<><div className="books-form-grid"><label><span>Vendor *</span><select required value={billForm.vendorId} onChange={(e)=>selectVendor(e.target.value)}><option value="">Select vendor</option>{vendors.map((vendor)=><option value={vendor.id} key={vendor.id}>{vendor.displayName}</option>)}</select></label><label><span>Vendor bill number *</span><input required value={billForm.billNumber} onChange={(e)=>setBillForm({...billForm,billNumber:e.target.value})}/></label><label><span>Bill date *</span><input type="date" required value={billForm.billDate} onChange={(e)=>setBillForm({...billForm,billDate:e.target.value})}/></label><label><span>Due date *</span><input type="date" min={billForm.billDate} required value={billForm.dueDate} onChange={(e)=>setBillForm({...billForm,dueDate:e.target.value})}/></label><label><span>Place of supply *</span><input maxLength={2} required value={billForm.placeOfSupply} onChange={(e)=>setBillForm({...billForm,placeOfSupply:e.target.value.replace(/\D/g,"")})}/></label></div>
      <div className="books-line-editor"><div className="books-line-head"><strong>Bill lines</strong><button type="button" onClick={()=>setBillForm({...billForm,lines:[...billForm.lines,blankLine()]})}><Plus/>Add line</button></div>{billForm.lines.map((line,index)=><div className="books-line-row" key={index}><label><span>Item</span><select value={line.itemId} onChange={(e)=>selectItem(index,e.target.value)}><option value="">Custom expense</option>{items.map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="line-description"><span>Description *</span><input required value={line.description} onChange={(e)=>updateLine(index,{description:e.target.value})}/></label><label><span>HSN/SAC</span><input value={line.hsnSac} onChange={(e)=>updateLine(index,{hsnSac:e.target.value.replace(/\D/g,"")})}/></label><label><span>Qty *</span><input required value={line.quantity} onChange={(e)=>updateLine(index,{quantity:e.target.value})}/></label><label><span>Rate *</span><input required value={line.unitPrice} onChange={(e)=>updateLine(index,{unitPrice:e.target.value})}/></label><label><span>GST %</span><input required value={line.gstRate} onChange={(e)=>updateLine(index,{gstRate:e.target.value})}/></label><button type="button" className="books-delete-line" disabled={billForm.lines.length===1} onClick={()=>setBillForm({...billForm,lines:billForm.lines.filter((_,i)=>i!==index)})}><Trash2/></button></div>)}</div>{formError&&<p className="books-form-error">{formError}</p>}<footer><button type="button" className="books-secondary" onClick={()=>setShowBill(false)}>Cancel</button><button className="books-primary" disabled={saving||!billForm.vendorId||!billForm.billNumber}>{saving?"Saving…":"Save bill draft"}</button></footer></>}</form></Modal>}
    {showExpense&&<Modal title="Record paid expense" description="This posts immediately: debit expense, credit cash." onClose={()=>setShowExpense(false)}><form className="books-modal-form" onSubmit={createExpense}><div className="books-form-grid"><label><span>Vendor</span><select value={expenseForm.vendorId} onChange={(e)=>setExpenseForm({...expenseForm,vendorId:e.target.value})}><option value="">No vendor</option>{vendors.map((vendor)=><option value={vendor.id} key={vendor.id}>{vendor.displayName}</option>)}</select></label><label><span>Date *</span><input type="date" required value={expenseForm.expenseDate} onChange={(e)=>setExpenseForm({...expenseForm,expenseDate:e.target.value})}/></label><label className="span-2"><span>Description *</span><input required value={expenseForm.description} onChange={(e)=>setExpenseForm({...expenseForm,description:e.target.value})}/></label><label><span>Amount *</span><div className="books-money-input"><IndianRupee/><input required value={expenseForm.amount} onChange={(e)=>setExpenseForm({...expenseForm,amount:e.target.value})}/></div></label></div>{formError&&<p className="books-form-error">{formError}</p>}<footer><button type="button" className="books-secondary" onClick={()=>setShowExpense(false)}>Cancel</button><button className="books-primary" disabled={saving||!expenseForm.description||!expenseForm.amount}>{saving?"Posting…":"Record & post expense"}</button></footer></form></Modal>}
    {postTarget&&<Modal title={`Post vendor bill ${postTarget.billNumber}?`} description="This creates the payable, expense and input-GST journal entry." onClose={()=>setPostTarget(null)}><div className="books-confirm"><span><CheckCircle2/></span><div><strong>{postTarget.vendorName}</strong><p>{inr(postTarget.grandTotal)} will be posted to the locked double-entry ledger.</p></div></div>{formError&&<p className="books-form-error">{formError}</p>}<footer className="books-modal-footer"><button className="books-secondary" onClick={()=>setPostTarget(null)}>Keep draft</button><button className="books-primary" disabled={saving} onClick={postBill}>{saving?"Posting…":"Post bill"}</button></footer></Modal>}
  </div>;
}

