import React, { useEffect, useState } from "react";
import { BadgeIndianRupee, Download, FileSpreadsheet, ReceiptIndianRupee, ShoppingCart } from "lucide-react";
import { booksApi, inr } from "../api";
import type { BooksOrganisation } from "../types";
import { ErrorState, LoadingState, PageHeader } from "./Common";

interface GstSummary { from:string; to:string; outward:{taxable:string;cgst:string;sgst:string;igst:string;totalTax:string;invoices:number;b2b:number;b2c:number}; inward:{taxable:string;cgst:string;sgst:string;igst:string;totalTax:string;bills:number}; netPayable:string }
const fyStart = () => { const now=new Date();const year=now.getMonth()<3?now.getFullYear()-1:now.getFullYear();return `${year}-04-01`; };

export default function GstPage({ organisation }:{ organisation:BooksOrganisation }) {
  const [from,setFrom]=useState(fyStart()); const [to,setTo]=useState(new Date().toISOString().slice(0,10)); const [data,setData]=useState<GstSummary|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const load=async()=>{setLoading(true);setError("");try{setData(await booksApi<GstSummary>(`/gst/summary?organisationId=${organisation.id}&from=${from}&to=${to}`));}catch(cause:any){setError(cause.message||"Unable to prepare GST summary");}finally{setLoading(false);}};
  useEffect(()=>{load();},[organisation.id,from,to]);
  const exportCsv=()=>{if(!data)return;const rows=[["INCroute Books GST Working Summary",organisation.legalName],["Period",`${from} to ${to}`],[],["Section","Taxable value","CGST","SGST","IGST","Total tax"],["Outward supplies",data.outward.taxable,data.outward.cgst,data.outward.sgst,data.outward.igst,data.outward.totalTax],["Inward supplies",data.inward.taxable,data.inward.cgst,data.inward.sgst,data.inward.igst,data.inward.totalTax],["Net payable","","","","",data.netPayable],[],["B2B invoices",data.outward.b2b],["B2C invoices",data.outward.b2c]];const csv=rows.map((row)=>row.map((cell)=>`"${String(cell??"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download=`gst-working-${from}-${to}.csv`;link.click();URL.revokeObjectURL(url);};
  if(loading)return <LoadingState label="Preparing GST working summary"/>;if(error||!data)return <ErrorState message={error||"GST data unavailable"} onRetry={load}/>;
  return <div className="books-page"><PageHeader eyebrow="India tax" title="GST working summary" description="Posted outward and inward supplies for review before return preparation." action={<div className="books-header-actions"><label>From <input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></label><label>To <input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></label><button className="books-secondary" onClick={exportCsv}><Download/>Export CSV</button></div>}/>
    <div className="books-gst-metrics"><div><span><ReceiptIndianRupee/></span><small>Outward taxable</small><strong>{inr(data.outward.taxable)}</strong><p>{data.outward.invoices} posted invoices · {data.outward.b2b} B2B · {data.outward.b2c} B2C</p></div><div><span><ShoppingCart/></span><small>Eligible input tax</small><strong>{inr(data.inward.totalTax)}</strong><p>{data.inward.bills} posted vendor bills</p></div><div className="highlight"><span><BadgeIndianRupee/></span><small>Net GST payable</small><strong>{inr(data.netPayable)}</strong><p>Output tax less recorded input tax</p></div></div>
    <div className="books-dashboard-grid"><section className="books-panel"><header><div><h2>Outward supply working</h2><p>Basis for GSTR-1 and GSTR-3B outward liability</p></div></header><div className="books-tax-breakdown"><p><span>Taxable value</span><strong>{inr(data.outward.taxable)}</strong></p><p><span>CGST</span><strong>{inr(data.outward.cgst)}</strong></p><p><span>SGST</span><strong>{inr(data.outward.sgst)}</strong></p><p><span>IGST</span><strong>{inr(data.outward.igst)}</strong></p><p className="total"><span>Total output tax</span><strong>{inr(data.outward.totalTax)}</strong></p></div></section><section className="books-panel"><header><div><h2>Inward supply working</h2><p>Input tax captured from posted vendor bills</p></div></header><div className="books-tax-breakdown"><p><span>Taxable value</span><strong>{inr(data.inward.taxable)}</strong></p><p><span>CGST</span><strong>{inr(data.inward.cgst)}</strong></p><p><span>SGST</span><strong>{inr(data.inward.sgst)}</strong></p><p><span>IGST</span><strong>{inr(data.inward.igst)}</strong></p><p className="total"><span>Total input tax</span><strong>{inr(data.inward.totalTax)}</strong></p></div></section></div>
    <div className="books-working-note"><FileSpreadsheet/><div><strong>Working report—not a filed return</strong><p>Live GST filing and GSTR-2B provider reconciliation remain disabled until the accounting MVP and ledger tests are stable.</p></div></div>
  </div>;
}

