import React, { useEffect, useState } from "react";
import { CheckCircle2, Download, FileBarChart, Scale } from "lucide-react";
import { booksApi, inr } from "../api";
import type { BooksOrganisation } from "../types";
import { EmptyState, ErrorState, LoadingState, PageHeader } from "./Common";

interface TrialBalance { asOf:string;accounts:Array<{id:string;code:string;name:string;type:string;subType:string;debit:string;credit:string}>;totals:{debit:string;credit:string;balanced:boolean} }
interface Financials { from:string;to:string;profitAndLoss:{rows:Array<{id:string;code:string;name:string;type:string;amount:string}>;totals:{income:string;expenses:string;netProfit:string}};balanceSheet:{rows:Array<{id:string;code:string;name:string;type:string;amount:string}>;totals:{assets:string;liabilities:string;equity:string;currentPeriodEarnings:string;balanced:boolean}} }
const fyStart=()=>{const date=new Date();const year=date.getMonth()<3?date.getFullYear()-1:date.getFullYear();return `${year}-04-01`;};

export default function ReportsPage({organisation}:{organisation:BooksOrganisation}) {
  const [tab,setTab]=useState<"trial"|"profit"|"balance">("trial");const[trial,setTrial]=useState<TrialBalance|null>(null);const[financials,setFinancials]=useState<Financials|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const [from,setFrom]=useState(fyStart());const[to,setTo]=useState(new Date().toISOString().slice(0,10));
  const load=async()=>{setLoading(true);setError("");try{const[trialData,financialData]=await Promise.all([booksApi<TrialBalance>(`/reports/trial-balance?organisationId=${organisation.id}&asOf=${to}`),booksApi<Financials>(`/reports/financials?organisationId=${organisation.id}&from=${from}&to=${to}`)]);setTrial(trialData);setFinancials(financialData);}catch(cause:any){setError(cause.message||"Unable to prepare reports");}finally{setLoading(false);}};
  useEffect(()=>{load();},[organisation.id,from,to]);
  const exportCsv=()=>{if(!trial||!financials)return;let rows:any[][]=[];if(tab==="trial")rows=[["Code","Account","Type","Debit","Credit"],...trial.accounts.map((a)=>[a.code,a.name,a.type,a.debit,a.credit]),["","Totals","",trial.totals.debit,trial.totals.credit]];else if(tab==="profit")rows=[["Code","Account","Class","Amount"],...financials.profitAndLoss.rows.map((a)=>[a.code,a.name,a.type,a.amount]),[],["","Income","",financials.profitAndLoss.totals.income],["","Expenses","",financials.profitAndLoss.totals.expenses],["","Net profit / loss","",financials.profitAndLoss.totals.netProfit]];else rows=[["Code","Account","Class","Amount"],...financials.balanceSheet.rows.map((a)=>[a.code,a.name,a.type,a.amount]),[],["","Assets","",financials.balanceSheet.totals.assets],["","Liabilities","",financials.balanceSheet.totals.liabilities],["","Equity","",financials.balanceSheet.totals.equity],["","Current earnings","",financials.balanceSheet.totals.currentPeriodEarnings]];const csv=rows.map((row)=>row.map((cell)=>`"${String(cell??"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download=`${tab}-report-${to}.csv`;link.click();URL.revokeObjectURL(url);};
  if(loading)return <LoadingState label="Preparing financial statements"/>;if(error||!trial||!financials)return <ErrorState message={error||"Reports unavailable"} onRetry={load}/>;
  const trialRows=trial.accounts.filter((a)=>Number(a.debit)||Number(a.credit));const plRows=financials.profitAndLoss.rows.filter((a)=>Number(a.amount));const bsRows=financials.balanceSheet.rows.filter((a)=>Number(a.amount));
  return <div className="books-page"><PageHeader eyebrow="Financial reports" title={tab==="trial"?"Trial balance":tab==="profit"?"Profit & loss":"Balance sheet"} description="Financial statements generated only from posted, tenant-scoped journal lines." action={<div className="books-header-actions"><label>From <input type="date" disabled={tab==="trial"||tab==="balance"} value={from} onChange={(e)=>setFrom(e.target.value)}/></label><label>To <input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></label><button className="books-secondary" onClick={exportCsv}><Download/>Export CSV</button></div>}/>
    <div className="books-segmented"><button className={tab==="trial"?"active":""} onClick={()=>setTab("trial")}>Trial balance</button><button className={tab==="profit"?"active":""} onClick={()=>setTab("profit")}>Profit & loss</button><button className={tab==="balance"?"active":""} onClick={()=>setTab("balance")}>Balance sheet</button></div>
    {tab==="trial"&&<><div className={`books-balance-banner ${trial.totals.balanced?"is-balanced":"is-unbalanced"}`}><span>{trial.totals.balanced?<CheckCircle2/>:<Scale/>}</span><div><strong>{trial.totals.balanced?"Ledger is balanced":"Ledger requires attention"}</strong><p>Total debits {inr(trial.totals.debit)} · Total credits {inr(trial.totals.credit)}</p></div></div><ReportTable rows={trialRows.map((a)=>({...a,amount:""}))} columns="trial" totals={[trial.totals.debit,trial.totals.credit]}/></>}
    {tab==="profit"&&<><div className="books-report-summary"><div><span>Income</span><strong>{inr(financials.profitAndLoss.totals.income)}</strong></div><div><span>Expenses</span><strong>{inr(financials.profitAndLoss.totals.expenses)}</strong></div><div className="highlight"><span>Net profit / loss</span><strong>{inr(financials.profitAndLoss.totals.netProfit)}</strong></div></div><ReportTable rows={plRows} columns="amount" totals={[financials.profitAndLoss.totals.netProfit]}/></>}
    {tab==="balance"&&<><div className={`books-balance-banner ${financials.balanceSheet.totals.balanced?"is-balanced":"is-unbalanced"}`}><span>{financials.balanceSheet.totals.balanced?<CheckCircle2/>:<Scale/>}</span><div><strong>{financials.balanceSheet.totals.balanced?"Balance sheet is balanced":"Balance sheet requires attention"}</strong><p>Assets equal liabilities, equity and current-period earnings.</p></div></div><div className="books-report-summary four"><div><span>Assets</span><strong>{inr(financials.balanceSheet.totals.assets)}</strong></div><div><span>Liabilities</span><strong>{inr(financials.balanceSheet.totals.liabilities)}</strong></div><div><span>Equity</span><strong>{inr(financials.balanceSheet.totals.equity)}</strong></div><div className="highlight"><span>Current earnings</span><strong>{inr(financials.balanceSheet.totals.currentPeriodEarnings)}</strong></div></div><ReportTable rows={bsRows} columns="amount" totals={[financials.balanceSheet.totals.assets]}/></>}
  </div>;
}

function ReportTable({rows,columns,totals}:{rows:any[];columns:"trial"|"amount";totals:string[]}){
  return <section className="books-panel books-table-panel">{rows.length?<div className="books-table-wrap"><table className="books-table"><thead><tr><th>Code</th><th>Account</th><th>Class</th>{columns==="trial"?<><th className="num">Debit</th><th className="num">Credit</th></>:<th className="num">Amount</th>}</tr></thead><tbody>{rows.map((a)=><tr key={a.id}><td><strong className="books-mono">{a.code}</strong></td><td><strong>{a.name}</strong></td><td>{a.type}</td>{columns==="trial"?<><td className="num">{Number(a.debit)?inr(a.debit):"—"}</td><td className="num">{Number(a.credit)?inr(a.credit):"—"}</td></>:<td className="num">{inr(a.amount)}</td>}</tr>)}</tbody>{columns==="trial"&&<tfoot><tr><td colSpan={3}>Total</td><td className="num">{inr(totals[0])}</td><td className="num">{inr(totals[1])}</td></tr></tfoot>}</table></div>:<EmptyState icon={FileBarChart} title="No posted balances yet" description="Drafts do not enter financial reports. Post a transaction to populate this statement."/>}</section>;
}

